CREATE TABLE IF NOT EXISTS quotes (
    id UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
    body TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NULL
);