// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: api/proto/quote/quote_service.proto

package quotepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QuoteServiceClient is the client API for QuoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuoteServiceClient interface {
	CreateQuote(ctx context.Context, in *CreateQuoteRequest, opts ...grpc.CallOption) (*CreateQuoteResponse, error)
	ListQuote(ctx context.Context, in *ListQouteRequest, opts ...grpc.CallOption) (*ListQuoteResponse, error)
	DetailQoute(ctx context.Context, in *DetailQuoteRequest, opts ...grpc.CallOption) (*DeleteQuoteResponse, error)
	UpdateQoute(ctx context.Context, in *UpdateQouteRequest, opts ...grpc.CallOption) (*UpdateQouteResponse, error)
	DeleteQouteRequest(ctx context.Context, in *DeleteQuoteRequest, opts ...grpc.CallOption) (*DeleteQuoteResponse, error)
}

type quoteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuoteServiceClient(cc grpc.ClientConnInterface) QuoteServiceClient {
	return &quoteServiceClient{cc}
}

func (c *quoteServiceClient) CreateQuote(ctx context.Context, in *CreateQuoteRequest, opts ...grpc.CallOption) (*CreateQuoteResponse, error) {
	out := new(CreateQuoteResponse)
	err := c.cc.Invoke(ctx, "/api.proto.quote.QuoteService/CreateQuote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) ListQuote(ctx context.Context, in *ListQouteRequest, opts ...grpc.CallOption) (*ListQuoteResponse, error) {
	out := new(ListQuoteResponse)
	err := c.cc.Invoke(ctx, "/api.proto.quote.QuoteService/ListQuote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) DetailQoute(ctx context.Context, in *DetailQuoteRequest, opts ...grpc.CallOption) (*DeleteQuoteResponse, error) {
	out := new(DeleteQuoteResponse)
	err := c.cc.Invoke(ctx, "/api.proto.quote.QuoteService/DetailQoute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) UpdateQoute(ctx context.Context, in *UpdateQouteRequest, opts ...grpc.CallOption) (*UpdateQouteResponse, error) {
	out := new(UpdateQouteResponse)
	err := c.cc.Invoke(ctx, "/api.proto.quote.QuoteService/UpdateQoute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) DeleteQouteRequest(ctx context.Context, in *DeleteQuoteRequest, opts ...grpc.CallOption) (*DeleteQuoteResponse, error) {
	out := new(DeleteQuoteResponse)
	err := c.cc.Invoke(ctx, "/api.proto.quote.QuoteService/DeleteQouteRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuoteServiceServer is the server API for QuoteService service.
// All implementations must embed UnimplementedQuoteServiceServer
// for forward compatibility
type QuoteServiceServer interface {
	CreateQuote(context.Context, *CreateQuoteRequest) (*CreateQuoteResponse, error)
	ListQuote(context.Context, *ListQouteRequest) (*ListQuoteResponse, error)
	DetailQoute(context.Context, *DetailQuoteRequest) (*DeleteQuoteResponse, error)
	UpdateQoute(context.Context, *UpdateQouteRequest) (*UpdateQouteResponse, error)
	DeleteQouteRequest(context.Context, *DeleteQuoteRequest) (*DeleteQuoteResponse, error)
	mustEmbedUnimplementedQuoteServiceServer()
}

// UnimplementedQuoteServiceServer must be embedded to have forward compatible implementations.
type UnimplementedQuoteServiceServer struct {
}

func (UnimplementedQuoteServiceServer) CreateQuote(context.Context, *CreateQuoteRequest) (*CreateQuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateQuote not implemented")
}
func (UnimplementedQuoteServiceServer) ListQuote(context.Context, *ListQouteRequest) (*ListQuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListQuote not implemented")
}
func (UnimplementedQuoteServiceServer) DetailQoute(context.Context, *DetailQuoteRequest) (*DeleteQuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetailQoute not implemented")
}
func (UnimplementedQuoteServiceServer) UpdateQoute(context.Context, *UpdateQouteRequest) (*UpdateQouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateQoute not implemented")
}
func (UnimplementedQuoteServiceServer) DeleteQouteRequest(context.Context, *DeleteQuoteRequest) (*DeleteQuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteQouteRequest not implemented")
}
func (UnimplementedQuoteServiceServer) mustEmbedUnimplementedQuoteServiceServer() {}

// UnsafeQuoteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuoteServiceServer will
// result in compilation errors.
type UnsafeQuoteServiceServer interface {
	mustEmbedUnimplementedQuoteServiceServer()
}

func RegisterQuoteServiceServer(s grpc.ServiceRegistrar, srv QuoteServiceServer) {
	s.RegisterService(&QuoteService_ServiceDesc, srv)
}

func _QuoteService_CreateQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).CreateQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.proto.quote.QuoteService/CreateQuote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).CreateQuote(ctx, req.(*CreateQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_ListQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListQouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).ListQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.proto.quote.QuoteService/ListQuote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).ListQuote(ctx, req.(*ListQouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_DetailQoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetailQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).DetailQoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.proto.quote.QuoteService/DetailQoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).DetailQoute(ctx, req.(*DetailQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_UpdateQoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateQouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).UpdateQoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.proto.quote.QuoteService/UpdateQoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).UpdateQoute(ctx, req.(*UpdateQouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_DeleteQouteRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).DeleteQouteRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.proto.quote.QuoteService/DeleteQouteRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).DeleteQouteRequest(ctx, req.(*DeleteQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuoteService_ServiceDesc is the grpc.ServiceDesc for QuoteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuoteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.proto.quote.QuoteService",
	HandlerType: (*QuoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateQuote",
			Handler:    _QuoteService_CreateQuote_Handler,
		},
		{
			MethodName: "ListQuote",
			Handler:    _QuoteService_ListQuote_Handler,
		},
		{
			MethodName: "DetailQoute",
			Handler:    _QuoteService_DetailQoute_Handler,
		},
		{
			MethodName: "UpdateQoute",
			Handler:    _QuoteService_UpdateQoute_Handler,
		},
		{
			MethodName: "DeleteQouteRequest",
			Handler:    _QuoteService_DeleteQouteRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/quote/quote_service.proto",
}
